# Generated by Django 2.1 on 2018-08-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstep', '0002_auto_20180814_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'managed': False},
        ),
    ]
