# Generated by Django 2.1 on 2018-08-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstep', '0003_auto_20180821_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'managed': True},
        ),
    ]
