# Generated by Django 2.1 on 2018-08-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstep', '0004_auto_20180821_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
    ]
