# Generated by Django 2.1 on 2018-08-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstep', '0005_auto_20180821_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'managed': False},
        ),
    ]
