# Generated by Django 2.1 on 2018-08-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstep', '0006_auto_20180821_1519'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
    ]
